# Nombre del workflow
name: CI/CD Frontend 

# Controla lo  que se va a ejecutar (Trigger) puede ser un pull, push, pull request
on: 
    push:
        branches: [release, develop, feature/auth ]

    pull_request:
        branches: [release, develop, feature/auth]

# Pasos a realizar
jobs:
    sistema-ventas-web:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: sistemas-ventas-web
        steps:
            - uses: actions/checkout@4 # Clona el repositorio actual
            - uses: actions/setup-node@4 # Usar Node
              with:
                node-version: 22.16.0 # Version de Node

            # Cargar cache de node_modules, para reducir tiempo de instalacion en proximas ejecuciones
            - name: Cache node modules
              id: node-cache
              uses: actions/cache@4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            # Instalar las dependencias
            - name: Install dependencies
              # No ejecutar si se  obtuvo node_modulesde cache
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: npm install


                



         
